name: "{repository-name}"
description: "{GitHub action description}"
author: "Sergey.S.Betke@yandex.ru"
branding:
  icon: "download"
  color: blue
inputs:
  version:
    description: "expected module version"
    required: false
    default: "latest"
  param-id:
    description: "param description"
    required: false
    default: "World"
  verbose:
    description: "verbose output"
    required: false
    default: "true"
outputs:
  output-id:
    description: "Random number"
    value: ${{ steps.main.outputs.output-id }}
runs:
  using: "composite"
  steps:
    - id: main
      shell: powershell
      run: |
        . "${{ github.action_path }}/Invoke-GitHubAction.ps1" `
          -ParamId "${{ inputs.param-id }}" `
          -Version "${{ inputs.version }}" `
          -Verbose:( "${{ inputs.verbose }}" -eq "true" ) `
        ;
